In [27]:
import pandas as pd
import numpy as np
import sqlite3
import seaborn as sns
import matplotlib.pyplot as plt
con=sqlite3.connect('database.sqlite')
filtered_data=pd.read_sql_query(
"""
    SELECT*
    FROM Reviews
    WHERE Score!=3
    """,con)

def partition(x):
    if x<3:
        return 0
    return 1

actualscore=filtered_data['Score']
posneg=actualscore.map(partition)
filtered_data['Score']=posneg

print(filtered_data)

            Id   ProductId          UserId                      ProfileName  \
0            1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1            2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2            3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3            4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4            5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   
...        ...         ...             ...                              ...   
525809  568450  B001EO7N10  A28KG5XORO54AY                 Lettie D. Carter   
525810  568451  B003S1WTCU  A3I8AFVPEE8KI5                        R. Sawyer   
525811  568452  B004I613EE  A121AA1GQV751Z                    pksd "pk_007"   
525812  568453  B004I613EE   A3IBEVCTXKNOH          Kathy A. Welch "katwel"   
525813  568454  B001LR2CU2  A3LGQPJCZVL9UC                         srfell17   

        HelpfulnessNumerator  HelpfulnessDenominato

In [28]:

final=filtered_data.drop_duplicates(subset={"UserId","ProfileName","Time","Text"},keep="first",inplace=False)
final=final[final.HelpfulnessNumerator<=final.HelpfulnessDenominator]

df=pd.DataFrame(final)
final=df.sample(2000)
print(final)

            Id   ProductId          UserId                     ProfileName  \
184152  199753  B000K8T3OQ   AML197X6XS3T8              Rosie Real "Rosie"   
91503    99538  B000ILIHA6  A1FVFTN6BYNLKB      Barbara M. Ross "barb1110"   
90940    98923  B005QRPH78  A39XAXOXLQODNC          Philly gal "phillygal"   
159592  173012  B000OUPSZI  A3SRDVCD2ATIIS                        Voltaire   
21558    23602  B001EO7GYY  A21MZJ84C2R7EQ  Mom and Teacher "Animal lover"   
...        ...         ...             ...                             ...   
203090  220033  B000FKIYKI   A8TMDTQR0E10S                             RCM   
509629  551057  B000XEV9YE   AKSVG13Q6MK6K                      M. Caserio   
73974    80490  B000I0CLK4   AUCISQA1YXX86                     Confederate   
290331  314523  B002V0PDJ0  A22JQVC4LU36GS              considered comment   
271437  294214  B000LKZ3GA   APCP6PLFLMUF2                           ptj71   

        HelpfulnessNumerator  HelpfulnessDenominator  Score    

In [30]:
final['Score'].value_counts()
x1=final[final['Score']==1]
x2=final[final['Score']==0]
print(x1)
print("**************************************************************************")
print(x2)

            Id   ProductId          UserId                     ProfileName  \
184152  199753  B000K8T3OQ   AML197X6XS3T8              Rosie Real "Rosie"   
91503    99538  B000ILIHA6  A1FVFTN6BYNLKB      Barbara M. Ross "barb1110"   
90940    98923  B005QRPH78  A39XAXOXLQODNC          Philly gal "phillygal"   
159592  173012  B000OUPSZI  A3SRDVCD2ATIIS                        Voltaire   
21558    23602  B001EO7GYY  A21MZJ84C2R7EQ  Mom and Teacher "Animal lover"   
...        ...         ...             ...                             ...   
203090  220033  B000FKIYKI   A8TMDTQR0E10S                             RCM   
509629  551057  B000XEV9YE   AKSVG13Q6MK6K                      M. Caserio   
73974    80490  B000I0CLK4   AUCISQA1YXX86                     Confederate   
290331  314523  B002V0PDJ0  A22JQVC4LU36GS              considered comment   
271437  294214  B000LKZ3GA   APCP6PLFLMUF2                           ptj71   

        HelpfulnessNumerator  HelpfulnessDenominator  Score    

In [31]:
from sklearn.utils import resample
x1=resample(x1,replace=True,n_samples=2000,random_state=123)
x2=resample(x2,replace=True,n_samples=2000,random_state=123)
print(x1)
print("*************************************************************************************************")
print(x2)

            Id   ProductId          UserId  \
402202  434873  B002AR158W  A12ENBT314RFXR   
510230  551694  B001P22K5U   ATV2QZ3VQU0ED   
454879  491788  B000AY9SR2  A2SS44O400KIZ7   
114981  124706  B004IV10EM  A133W8PZ48AXW0   
307684  333225  B002YJCACG   A48EZQPDK5AMW   
...        ...         ...             ...   
3553      3860  B001M074MY  A1ZZZT0KJR46UV   
47176    51304  B001LM42JG  A12PCM7NM52K34   
182104  197510  B0012Y0HA6   A2P9U0NJNYGST   
345608  373877  B004WTHCO2  A1NWSKX1U7QUKS   
369313  399299  B002QXJ7OY   AQT95GTVJLVFE   

                                ProfileName  HelpfulnessNumerator  \
402202  P. Gray "The Gluten Free Assistant"                     0   
510230                 B. Leach "Spider444"                     0   
454879                                carol                     1   
114981                    Sheila "sheila40"                     0   
307684                      Sunny Muthumari                     0   
...                              

In [32]:
final=pd.concat([x1,x2])
print(final)

            Id   ProductId          UserId  \
402202  434873  B002AR158W  A12ENBT314RFXR   
510230  551694  B001P22K5U   ATV2QZ3VQU0ED   
454879  491788  B000AY9SR2  A2SS44O400KIZ7   
114981  124706  B004IV10EM  A133W8PZ48AXW0   
307684  333225  B002YJCACG   A48EZQPDK5AMW   
...        ...         ...             ...   
441565  477473  B001FA1LQ6  A29313797NGT9L   
335746  363280  B002483V5C  A1TUX0BB8L2RE4   
510988  552511  B000CQ01L0  A2CU0WYTQHTFFL   
489586  529387  B0047IPC2W  A1X654WESTE8JF   
42102    45779  B0041NYV8E  A29M09QBG9TZLP   

                                         ProfileName  HelpfulnessNumerator  \
402202           P. Gray "The Gluten Free Assistant"                     0   
510230                          B. Leach "Spider444"                     0   
454879                                         carol                     1   
114981                             Sheila "sheila40"                     0   
307684                               Sunny Muthumari     

In [33]:
final['Score'].value_counts()

1    2000
0    2000
Name: Score, dtype: int64

In [34]:
final=final.sort_values('Time',axis=0,ascending=True)
print(final)

            Id   ProductId          UserId  \
61299    66610  B0000SY9U4  A3EEDHNHI4WNSH   
61299    66610  B0000SY9U4  A3EEDHNHI4WNSH   
227761  246969  B0002HDM06   AS7SWC0HK8SV8   
436415  471918  B0000UC7RE  A2IXA0SK3PQIRU   
436415  471918  B0000UC7RE  A2IXA0SK3PQIRU   
...        ...         ...             ...   
442739  478718  B00529PECI  A3H4L7TJKQHW4Q   
442739  478718  B00529PECI  A3H4L7TJKQHW4Q   
442739  478718  B00529PECI  A3H4L7TJKQHW4Q   
442739  478718  B00529PECI  A3H4L7TJKQHW4Q   
442739  478718  B00529PECI  A3H4L7TJKQHW4Q   

                                           ProfileName  HelpfulnessNumerator  \
61299                                  Joanna J. Young                    23   
61299                                  Joanna J. Young                    23   
227761                               Mary Louise Baker                    15   
436415                                       A. Murphy                     6   
436415                                       A.

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf_idf_vect=TfidfVectorizer(analyzer='word',ngram_range=(1,2),stop_words='english')
final_tf_idf=tf_idf_vect.fit_transform(final['Text'].values)
final_tf_idf.get_shape()

(4000, 52633)

In [36]:
features=tf_idf_vect.get_feature_names()
print(features)

['00', '00 bottle', '00 box', '00 gift', '00 good', '00 item', '00 oz', '00 plus', '00 price', '00 probably', '00 shipping', '00 tin', '000', '000 feet', '01', '01 08', '02', '02 amazon', '05', '05 shipping', '08', '08 october', '0g', '0g sodium', '0g trans', '10', '10 12', '10 15', '10 30', '10 75', '10 apples', '10 bottle', '10 br', '10 calcium', '10 calories', '10 cent', '10 cup', '10 day', '10 degrees', '10 enjoyed', '10 fruits', '10 hours', '10 inch', '10 lb', '10 lbs', '10 low', '10 mins', '10 minutes', '10 month', '10 ounces', '10 packet', '10 piece', '10 seconds', '10 small', '10 star', '10 strips', '10 tall', '10 time', '10 truffle', '10 year', '10 years', '100', '100 200', '100 arabica', '100 bad', '100 bags', '100 cacao', '100 cal', '100 calorie', '100 calories', '100 chicken', '100 colombian', '100 count', '100 fruit', '100 kona', '100 mg', '100 natural', '100 organic', '100 rda', '100 virgin', '1000s', '1000s documented', '100x', '100x better', '105', '105 calories', '108'

In [54]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler(with_mean=False)
final_tf_idf=ss.fit_transform(final_tf_idf)
final_matrix=final_tf_idf.todense()
print(final_tf_idf)
print("**************************************************************************************************")
print("**************************************************************************************************")
print((final_matrix))


  (0, 40136)	44.73254408425844
  (0, 43690)	44.73254408425844
  (0, 34662)	44.73254408425844
  (0, 21207)	44.73254408425844
  (0, 20466)	44.73254408425844
  (0, 20304)	44.73254408425844
  (0, 25738)	44.73254408425844
  (0, 16620)	44.73254408425844
  (0, 19818)	44.73254408425844
  (0, 31826)	12.726149563155296
  (0, 38951)	44.73254408425844
  (0, 36046)	30.23824713525833
  (0, 45149)	44.73254408425844
  (0, 13415)	44.73254408425844
  (0, 34793)	44.73254408425844
  (0, 20305)	44.73254408425844
  (0, 40964)	44.73254408425844
  (0, 9881)	44.73254408425844
  (0, 20869)	44.73254408425844
  (0, 24352)	44.73254408425844
  (0, 29717)	44.73254408425844
  (0, 32581)	44.73254408425844
  (0, 9842)	15.137426593114613
  (0, 37261)	44.73254408425844
  (0, 21548)	44.73254408425844
  :	:
  (3999, 39980)	28.301965507088997
  (3999, 18404)	28.301965507088997
  (3999, 43921)	28.301965507088997
  (3999, 48523)	28.301965507088997
  (3999, 25389)	28.301965507088997
  (3999, 37673)	28.301965507088997
  (3999, 

In [18]:
X_train,X_test=np.split(final_matrix,[int(0.7*(len(final_tf_idf)))]);
y_train,y_test=np.split(final['Score'],[int(0.7*len(final['Score']))]);
tuned_parameters=[{'C':[10**-3,10**-2,10**-1,10**0,10**1,10**2,10**3]}]
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
model=GridSearchCV(LogisticRegression(),tuned_parameters,scoring='f1',cv=10)
model.fit(X_train,y_train)
print(model.best_estimator_)

C:\Users\aditya raj\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\aditya raj\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\aditya raj\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\aditya raj\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\aditya raj\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Spec

C:\Users\aditya raj\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\aditya raj\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\aditya raj\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\aditya raj\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\aditya raj\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Spec

LogisticRegression(C=0.001, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)


In [19]:
print(model.score(X_test,y_test))

0.7284035936420179


In [68]:
final_matrix=final_tf_idf.todense()
print(final_matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [70]:
count=np.count_nonzero(final_matrix)
print(count)

271513
